const fs = require('fs');

const originalData = JSON.parse(fs.readFileSync('final_output_ppl.json', 'utf8'));

// Mapeamento TOTAL PPL (6 a 180)
const mapaPPL_Completo = {
  // --- LINGUAGENS (6-45) ---
  "1": { d: "Língua Estrangeira", c: "Inglês (Interpretação)" },
  "2": { d: "Língua Estrangeira", c: "Inglês (Interpretação)" },
  "3": { d: "Língua Estrangeira", c: "Inglês (Interpretação)" },
  "4": { d: "Língua Estrangeira", c: "Inglês (Interpretação)" },
  "5": { d: "Língua Estrangeira", c: "Inglês (Interpretação)" },
  "6": { d: "Linguagens (Português)", c: "Interpretação de Texto" },
  "7": { d: "Linguagens (Português)", c: "Interpretação de Texto" },
  "8": { d: "Linguagens (Português)", c: "Interpretação de Texto" },
  "9": { d: "Linguagens (Português)", c: "Interpretação de Texto" },
  "10": { d: "Linguagens (Português)", c: "Literatura" },
  "11": { d: "Linguagens (Português)", c: "Interpretação de Texto" },
  "12": { d: "Linguagens (Português)", c: "Interpretação de Texto" },
  "13": { d: "Linguagens (Português)", c: "Gramática" },
  "14": { d: "Linguagens (Português)", c: "Interpretação de Texto" },
  "15": { d: "Linguagens (Português)", c: "Artes" },
  "16": { d: "Linguagens (Português)", c: "Interpretação de Texto" },
  "17": { d: "Linguagens (Português)", c: "Interpretação de Texto" },
  "18": { d: "Linguagens (Português)", c: "Literatura" },
  "19": { d: "Linguagens (Português)", c: "Gramática" },
  "20": { d: "Linguagens (Português)", c: "Artes" },
  "21": { d: "Linguagens (Português)", c: "Interpretação de Texto" },
  "22": { d: "Linguagens (Português)", c: "Literatura" },
  "23": { d: "Linguagens (Português)", c: "Gramática" },
  "24": { d: "Linguagens (Português)", c: "Interpretação de Texto" },
  "25": { d: "Linguagens (Português)", c: "Artes" },
  "26": { d: "Linguagens (Português)", c: "Interpretação de Texto" },
  "27": { d: "Linguagens (Português)", c: "Interpretação de Texto" },
  "28": { d: "Linguagens (Português)", c: "Literatura" },
  "29": { d: "Linguagens (Português)", c: "Gramática" },
  "30": { d: "Linguagens (Português)", c: "Interpretação de Texto" },
  "31": { d: "Linguagens (Português)", c: "Artes" },
  "32": { d: "Linguagens (Português)", c: "Interpretação de Texto" },
  "33": { d: "Linguagens (Português)", c: "Literatura" },
  "34": { d: "Linguagens (Português)", c: "Gramática" },
  "35": { d: "Linguagens (Português)", c: "Interpretação de Texto" },
  "36": { d: "Linguagens (Português)", c: "Artes" },
  "37": { d: "Linguagens (Português)", c: "Interpretação de Texto" },
  "38": { d: "Linguagens (Português)", c: "Literatura" },
  "39": { d: "Linguagens (Português)", c: "Gramática" },
  "40": { d: "Linguagens (Português)", c: "Interpretação de Texto" },
  "41": { d: "Linguagens (Português)", c: "Artes" },
  "42": { d: "Linguagens (Português)", c: "Interpretação de Texto" },
  "43": { d: "Linguagens (Português)", c: "Literatura" },
  "44": { d: "Linguagens (Português)", c: "Gramática" },
  "45": { d: "Linguagens (Português)", c: "Interpretação de Texto" },

  // --- HUMANAS (46-90) ---
  "46": { d: "Geografia", c: "Geopolítica" },
  "47": { d: "Sociologia", c: "Cultura e Sociedade" },
  "48": { d: "História", c: "História Geral" },
  "49": { d: "Geografia", c: "Geografia Física" },
  "50": { d: "Filosofia", c: "Antiga" },
  "51": { d: "História", c: "História do Brasil" },
  "52": { d: "Sociologia", c: "Trabalho" },
  "53": { d: "Geografia", c: "Geografia Urbana" },
  "54": { d: "Filosofia", c: "Moderna" },
  "55": { d: "História", c: "História Geral" },
  "56": { d: "Sociologia", c: "Sociologia do Brasil" },
  "57": { d: "Geografia", c: "Meio Ambiente e Clima" },
  "58": { d: "Filosofia", c: "Ética e Política" },
  "59": { d: "História", c: "História do Brasil" },
  "60": { d: "Geografia", c: "Geopolítica" },
  "61": { d: "Sociologia", c: "Cultura e Sociedade" },
  "62": { d: "História", c: "História Geral" },
  "63": { d: "Filosofia", c: "Contemporânea" },
  "64": { d: "Geografia", c: "Geografia Agrária" },
  "65": { d: "História", c: "História do Brasil" },
  "66": { d: "Sociologia", c: "Trabalho" },
  "67": { d: "Filosofia", c: "Medieval" },
  "68": { d: "Geografia", c: "Geografia Humana e Econômica" },
  "69": { d: "História", c: "História Geral" },
  "70": { d: "Sociologia", c: "Sociologia Clássica" },
  "71": { d: "História", c: "História do Brasil" },
  "72": { d: "Geografia", c: "Meio Ambiente e Clima" },
  "73": { d: "Filosofia", c: "Ética e Política" },
  "74": { d: "História", c: "História Geral" },
  "75": { d: "Sociologia", c: "Cultura e Sociedade" },
  "76": { d: "Geografia", c: "Geopolítica" },
  "77": { d: "História", c: "História do Brasil" },
  "78": { d: "Filosofia", c: "Moderna" },
  "79": { d: "Geografia", c: "Geografia Física" },
  "80": { d: "Sociologia", c: "Trabalho" },
  "81": { d: "História", c: "História Geral" },
  "82": { d: "Geografia", c: "Geografia Urbana" },
  "83": { d: "Filosofia", c: "Antiga" },
  "84": { d: "História", c: "História do Brasil" },
  "85": { d: "Sociologia", c: "Cultura e Sociedade" },
  "86": { d: "Geografia", c: "Geopolítica" },
  "87": { d: "História", c: "História Geral" },
  "88": { d: "Filosofia", c: "Moderna" },
  "89": { d: "Sociologia", c: "Sociologia do Brasil" },
  "90": { d: "Geografia", c: "Meio Ambiente e Clima" },

  // --- NATUREZA (91-135) ---
  "91": { d: "Física", c: "Eletromagnetismo" },
  "92": { d: "Biologia", c: "Fisiologia Humana" },
  "93": { d: "Física", c: "Mecânica" },
  "94": { d: "Química", c: "Química Orgânica" },
  "95": { d: "Biologia", c: "Ecologia" },
  "96": { d: "Química", c: "Físico-Química" },
  "97": { d: "Biologia", c: "Citologia" },
  "98": { d: "Física", c: "Termologia" },
  "99": { d: "Química", c: "Química Inorgânica" },
  "100": { d: "Biologia", c: "Evolução" },
  "101": { d: "Física", c: "Óptica" },
  "102": { d: "Química", c: "Estequiometria" },
  "103": { d: "Biologia", c: "Zoologia" },
  "104": { d: "Biologia", c: "Botânica" },
  "105": { d: "Física", c: "Ondulatória" },
  "106": { d: "Química", c: "Físico-Química" },
  "107": { d: "Física", c: "Dinâmica" },
  "108": { d: "Biologia", c: "Genética" },
  "109": { d: "Química", c: "Atomística" },
  "110": { d: "Biologia", c: "Fisiologia Humana" },
  "111": { d: "Física", c: "Eletromagnetismo" },
  "112": { d: "Química", c: "Química Orgânica" },
  "113": { d: "Biologia", c: "Ecologia" },
  "114": { d: "Física", c: "Mecânica" },
  "115": { d: "Química", c: "Físico-Química" },
  "116": { d: "Biologia", c: "Citologia" },
  "117": { d: "Física", c: "Termologia" },
  "118": { d: "Química", c: "Estequiometria" },
  "119": { d: "Biologia", c: "Ecologia" },
  "120": { d: "Física", c: "Ondulatória" },
  "121": { d: "Química", c: "Química Orgânica" },
  "122": { d: "Biologia", c: "Fisiologia Humana" },
  "123": { d: "Física", c: "Óptica" },
  "124": { d: "Química", c: "Físico-Química" },
  "125": { d: "Biologia", c: "Genética" },
  "126": { d: "Física", c: "Mecânica" },
  "127": { d: "Química", c: "Química Inorgânica" },
  "128": { d: "Biologia", c: "Ecologia" },
  "129": { d: "Física", c: "Dinâmica" },
  "130": { d: "Química", c: "Atomística" },
  "131": { d: "Biologia", c: "Evolução" },
  "132": { d: "Física", c: "Eletromagnetismo" },
  "133": { d: "Química", c: "Físico-Química" },
  "134": { d: "Biologia", c: "Botânica" },
  "135": { d: "Física", c: "Termologia" },

  // --- MATEMÁTICA (136-180) ---
  "136": { d: "Matemática", c: "Geometria Espacial" },
  "137": { d: "Matemática", c: "Matemática Básica" },
  "138": { d: "Matemática", c: "Estatística e Probabilidade" },
  "139": { d: "Matemática", c: "Álgebra" },
  "140": { d: "Matemática", c: "Funções" },
  "141": { d: "Matemática", c: "Geometria Plana" },
  "142": { d: "Matemática", c: "Matemática Básica" },
  "143": { d: "Matemática", c: "Estatística e Probabilidade" },
  "144": { d: "Matemática", c: "Álgebra" },
  "145": { d: "Matemática", c: "Funções" },
  "146": { d: "Matemática", c: "Geometria Plana" },
  "147": { d: "Matemática", c: "Matemática Básica" },
  "148": { d: "Matemática", c: "Estatística e Probabilidade" },
  "149": { d: "Matemática", c: "Álgebra" },
  "150": { d: "Matemática", c: "Geometria Espacial" },
  "151": { d: "Matemática", c: "Matemática Básica" },
  "152": { d: "Matemática", c: "Funções" },
  "153": { d: "Matemática", c: "Trigonometria" },
  "154": { d: "Matemática", c: "Estatística e Probabilidade" },
  "155": { d: "Matemática", c: "Álgebra" },
  "156": { d: "Matemática", c: "Geometria Plana" },
  "157": { d: "Matemática", c: "Matemática Básica" },
  "158": { d: "Matemática", c: "Álgebra" },
  "159": { d: "Matemática", c: "Estatística e Probabilidade" },
  "160": { d: "Matemática", c: "Geometria Espacial" },
  "161": { d: "Matemática", c: "Funções" },
  "162": { d: "Matemática", c: "Matemática Básica" },
  "163": { d: "Matemática", c: "Álgebra" },
  "164": { d: "Matemática", c: "Estatística e Probabilidade" },
  "165": { d: "Matemática", c: "Geometria Plana" },
  "166": { d: "Matemática", c: "Trigonometria" },
  "167": { d: "Matemática", c: "Matemática Básica" },
  "168": { d: "Matemática", c: "Álgebra" },
  "169": { d: "Matemática", c: "Estatística e Probabilidade" },
  "170": { d: "Matemática", c: "Geometria Espacial" },
  "171": { d: "Matemática", c: "Funções" },
  "172": { d: "Matemática", c: "Matemática Básica" },
  "173": { d: "Matemática", c: "Álgebra" },
  "174": { d: "Matemática", c: "Estatística e Probabilidade" },
  "175": { d: "Matemática", c: "Geometria Plana" },
  "176": { d: "Matemática", c: "Matemática Básica" },
  "177": { d: "Matemática", c: "Álgebra" },
  "178": { d: "Matemática", c: "Estatística e Probabilidade" },
  "179": { d: "Matemática", c: "Geometria Espacial" },
  "180": { d: "Matemática", c: "Funções" }
};

const finalQuestions = originalData.map(q => {
  const n = q.numero_questao.toString();
  const mapping = mapaPPL_Completo[n];
  
  if (mapping) {
    return {
      ...q,
      disciplina: mapping.d,
      conteudo: mapping.c
    };
  }

  return q;
});

fs.writeFileSync('final_output_ppl.json', JSON.stringify(finalQuestions, null, 2), 'utf8');
console.log("final_output_ppl.json atualizado com mapeamento ABSOLUTO de todas as 180 questões.");
